import { MarketplaceItem, MarketplaceCategory } from '../../types/marketplace';

export const marketplaceCategories: MarketplaceCategory[] = [
  { id: '1', name: 'Electronics', slug: 'electronics' },
  { id: '2', name: 'Furniture', slug: 'furniture' },
  { id: '3', name: 'Clothing', slug: 'clothing' },
  { id: '4', name: 'Books', slug: 'books' },
  { id: '5', name: 'Sports', slug: 'sports' },
  { id: '6', name: 'Vehicles', slug: 'vehicles' },
  { id: '7', name: 'Toys & Games', slug: 'toys-games' },
  { id: '8', name: 'Home & Garden', slug: 'home-garden' },
  { id: '9', name: 'Audio', slug: 'audio' },
  { id: '10', name: 'Photography', slug: 'photography' },
  { id: '11', name: 'Accessories', slug: 'accessories' },
  { id: '12', name: 'Kitchen', slug: 'kitchen' },
];

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: '1',
    title: 'MacBook Pro 16" 2021',
    description: 'M1 Pro, 16GB RAM, 512GB SSD, Space Gray, excellent condition. Only used for 6 months, selling because I got a new one from work.',
    price: 1800,
    currency: 'USD',
    imageUrl: '/images/marketplace/macbook.jpg',
    category: 'Electronics',
    condition: 'Like New',
    location: 'Berkeley, CA',
    sellerId: 'user1',
    sellerName: 'John Doe',
    createdAt: '2023-05-15T10:30:00Z',
    updatedAt: '2023-05-15T10:30:00Z',
  },
  {
    id: '2',
    title: 'Wooden Dining Table',
    description: 'Solid oak dining table with 6 chairs, minor scratches. Perfect for family gatherings and dinner parties. Chairs are upholstered with beige fabric.',
    price: 350,
    currency: 'USD',
    imageUrl: '/images/marketplace/dining-table.jpg',
    category: 'Furniture',
    condition: 'Good',
    location: 'Oakland, CA',
    sellerId: 'user2',
    sellerName: 'Jane Smith',
    createdAt: '2023-05-10T14:20:00Z',
    updatedAt: '2023-05-10T14:20:00Z',
  },
  {
    id: '3',
    title: 'Nike Air Jordan 1',
    description: 'Size 10, Chicago colorway, worn once. Original box and extra laces included. No scuffs or marks, practically brand new.',
    price: 220,
    currency: 'USD',
    imageUrl: '/images/marketplace/air-jordan.jpg',
    category: 'Clothing',
    condition: 'Like New',
    location: 'San Francisco, CA',
    sellerId: 'user3',
    sellerName: 'Mike Johnson',
    createdAt: '2023-05-12T09:15:00Z',
    updatedAt: '2023-05-12T09:15:00Z',
  },
  {
    id: '4',
    title: 'iPhone 13 Pro',
    description: '256GB, Sierra Blue, unlocked, includes charger and case. Battery health at 92%, no scratches or dents. AppleCare+ until December 2023.',
    price: 750,
    currency: 'USD',
    imageUrl: '/images/marketplace/iphone.jpg',
    category: 'Electronics',
    condition: 'Good',
    location: 'Berkeley, CA',
    sellerId: 'user4',
    sellerName: 'Sarah Williams',
    createdAt: '2023-05-14T16:45:00Z',
    updatedAt: '2023-05-14T16:45:00Z',
  },
  {
    id: '5',
    title: 'Calculus Textbook',
    description: 'Calculus: Early Transcendentals, 8th Edition, James Stewart. Minimal highlighting, all pages intact. Perfect for Math 1A/1B courses.',
    price: 45,
    currency: 'USD',
    imageUrl: '/images/marketplace/textbook.jpg',
    category: 'Books',
    condition: 'Good',
    location: 'Berkeley, CA',
    sellerId: 'user5',
    sellerName: 'Alex Chen',
    createdAt: '2023-05-08T11:30:00Z',
    updatedAt: '2023-05-08T11:30:00Z',
  },
  {
    id: '6',
    title: 'Mountain Bike',
    description: 'Trek Marlin 7, 29" wheels, hydraulic disc brakes, used for one season. Recently tuned up, new chain and brake pads. Perfect for trails around Berkeley.',
    price: 650,
    currency: 'USD',
    imageUrl: '/images/marketplace/bike.jpg',
    category: 'Sports',
    condition: 'Good',
    location: 'Oakland, CA',
    sellerId: 'user6',
    sellerName: 'David Brown',
    createdAt: '2023-05-11T13:20:00Z',
    updatedAt: '2023-05-11T13:20:00Z',
  },
  {
    id: '7',
    title: 'IKEA MALM Dresser',
    description: '6-drawer dresser, white, assembled, good condition. Dimensions: 63" width, 30" height, 19" depth. No scratches or damage.',
    price: 120,
    currency: 'USD',
    imageUrl: '/images/marketplace/dresser.jpg',
    category: 'Furniture',
    condition: 'Good',
    location: 'San Francisco, CA',
    sellerId: 'user7',
    sellerName: 'Emily Davis',
    createdAt: '2023-05-09T10:10:00Z',
    updatedAt: '2023-05-09T10:10:00Z',
  },
  {
    id: '8',
    title: 'Sony PlayStation 5',
    description: 'Disc edition, includes controller and 2 games (Spider-Man: Miles Morales and Demon\'s Souls). Original box and all cables included.',
    price: 450,
    currency: 'USD',
    imageUrl: '/images/marketplace/ps5.jpg',
    category: 'Electronics',
    condition: 'Like New',
    location: 'Berkeley, CA',
    sellerId: 'user8',
    sellerName: 'Tom Wilson',
    createdAt: '2023-05-13T15:30:00Z',
    updatedAt: '2023-05-13T15:30:00Z',
  },
  {
    id: '9',
    title: 'Dell 27" 4K Monitor',
    description: 'Dell UltraSharp U2720Q 27" 4K USB-C Monitor. Perfect for productivity and content creation. Includes original stand and power cable.',
    price: 320,
    currency: 'USD',
    imageUrl: '/images/marketplace/monitor.jpg',
    category: 'Electronics',
    condition: 'Good',
    location: 'Berkeley, CA',
    sellerId: 'user1',
    sellerName: 'John Doe',
    createdAt: '2023-05-16T09:45:00Z',
    updatedAt: '2023-05-16T09:45:00Z',
  },
  {
    id: '10',
    title: 'Sony WH-1000XM4 Headphones',
    description: 'Wireless noise-cancelling headphones, black. Includes carrying case, charging cable, and audio cable. Great battery life and sound quality.',
    price: 180,
    currency: 'USD',
    imageUrl: '/images/marketplace/headphones.jpg',
    category: 'Electronics',
    condition: 'Good',
    location: 'Oakland, CA',
    sellerId: 'user3',
    sellerName: 'Mike Johnson',
    createdAt: '2023-05-17T14:20:00Z',
    updatedAt: '2023-05-17T14:20:00Z',
  },
  {
    id: '11',
    title: 'Canon EOS R6 Camera',
    description: 'Full-frame mirrorless camera with 24-105mm lens. Includes 2 batteries, charger, 64GB SD card, and camera bag. Only 5,000 shutter count.',
    price: 2200,
    currency: 'USD',
    imageUrl: '/images/marketplace/camera.jpg',
    category: 'Photography',
    condition: 'Like New',
    location: 'San Francisco, CA',
    sellerId: 'user5',
    sellerName: 'Alex Chen',
    createdAt: '2023-05-18T11:15:00Z',
    updatedAt: '2023-05-18T11:15:00Z',
  },
  {
    id: '12',
    title: 'Apple Watch Series 7',
    description: '45mm, GPS + Cellular, Midnight Aluminum Case with Midnight Sport Band. Used for 3 months, no scratches. Original box and charger included.',
    price: 300,
    currency: 'USD',
    imageUrl: '/images/marketplace/watch.jpg',
    category: 'Electronics',
    condition: 'Like New',
    location: 'Berkeley, CA',
    sellerId: 'user2',
    sellerName: 'Jane Smith',
    createdAt: '2023-05-19T16:30:00Z',
    updatedAt: '2023-05-19T16:30:00Z',
  },
  {
    id: '13',
    title: 'Fender Stratocaster Electric Guitar',
    description: 'American Professional II Stratocaster, Dark Night finish. Includes hardshell case, strap, and cable. Barely played, in perfect condition.',
    price: 1400,
    currency: 'USD',
    imageUrl: '/images/marketplace/guitar.jpg',
    category: 'Audio',
    condition: 'Like New',
    location: 'Oakland, CA',
    sellerId: 'user6',
    sellerName: 'David Brown',
    createdAt: '2023-05-20T10:45:00Z',
    updatedAt: '2023-05-20T10:45:00Z',
  },
  {
    id: '14',
    title: 'Standing Desk',
    description: 'Fully Jarvis Standing Desk, 60" x 30", bamboo top with black frame. Electric height adjustment, memory settings. Includes cable management tray.',
    price: 400,
    currency: 'USD',
    imageUrl: '/images/marketplace/desk.jpg',
    category: 'Furniture',
    condition: 'Good',
    location: 'San Francisco, CA',
    sellerId: 'user4',
    sellerName: 'Sarah Williams',
    createdAt: '2023-05-21T13:20:00Z',
    updatedAt: '2023-05-21T13:20:00Z',
  },
  {
    id: '15',
    title: 'Herman Miller Aeron Chair',
    description: 'Size B, fully adjustable with lumbar support. Graphite color. 2 years old but in excellent condition. Perfect for home office or studying.',
    price: 550,
    currency: 'USD',
    imageUrl: '/images/marketplace/chair.jpg',
    category: 'Furniture',
    condition: 'Good',
    location: 'Berkeley, CA',
    sellerId: 'user7',
    sellerName: 'Emily Davis',
    createdAt: '2023-05-22T09:10:00Z',
    updatedAt: '2023-05-22T09:10:00Z',
  },
  {
    id: '16',
    title: 'Modern Floor Lamp',
    description: 'Arched floor lamp with marble base, brushed brass finish. Height adjustable, dimmable LED light. Perfect for living room or reading corner.',
    price: 120,
    currency: 'USD',
    imageUrl: '/images/marketplace/lamp.jpg',
    category: 'Home & Garden',
    condition: 'Good',
    location: 'Oakland, CA',
    sellerId: 'user8',
    sellerName: 'Tom Wilson',
    createdAt: '2023-05-23T15:40:00Z',
    updatedAt: '2023-05-23T15:40:00Z',
  },
  {
    id: '17',
    title: 'North Face Backpack',
    description: 'Borealis backpack, 28L capacity, black. Laptop sleeve fits up to 15" laptop. Water-resistant, multiple compartments. Used for one semester.',
    price: 65,
    currency: 'USD',
    imageUrl: '/images/marketplace/backpack.jpg',
    category: 'Accessories',
    condition: 'Good',
    location: 'Berkeley, CA',
    sellerId: 'user1',
    sellerName: 'John Doe',
    createdAt: '2023-05-24T11:25:00Z',
    updatedAt: '2023-05-24T11:25:00Z',
  },
  {
    id: '18',
    title: 'Adidas Ultraboost Sneakers',
    description: 'Ultraboost 21, size 9, core black/grey. Worn a few times, very comfortable for running or casual wear. Original box included.',
    price: 90,
    currency: 'USD',
    imageUrl: '/images/marketplace/sneakers.jpg',
    category: 'Clothing',
    condition: 'Good',
    location: 'San Francisco, CA',
    sellerId: 'user3',
    sellerName: 'Mike Johnson',
    createdAt: '2023-05-25T14:15:00Z',
    updatedAt: '2023-05-25T14:15:00Z',
  },
  {
    id: '19',
    title: 'Patagonia Down Jacket',
    description: 'Men\'s Down Sweater Jacket, size M, navy blue. 800-fill-power goose down, water-repellent shell. Perfect for Bay Area weather.',
    price: 150,
    currency: 'USD',
    imageUrl: '/images/marketplace/jacket.jpg',
    category: 'Clothing',
    condition: 'Good',
    location: 'Berkeley, CA',
    sellerId: 'user5',
    sellerName: 'Alex Chen',
    createdAt: '2023-05-26T10:30:00Z',
    updatedAt: '2023-05-26T10:30:00Z',
  },
  {
    id: '20',
    title: 'Ray-Ban Sunglasses',
    description: 'Original Wayfarer Classic, black frame with green G-15 lenses. Includes case and cleaning cloth. Barely worn, no scratches.',
    price: 95,
    currency: 'USD',
    imageUrl: '/images/marketplace/sunglasses.jpg',
    category: 'Accessories',
    condition: 'Like New',
    location: 'Oakland, CA',
    sellerId: 'user2',
    sellerName: 'Jane Smith',
    createdAt: '2023-05-27T13:45:00Z',
    updatedAt: '2023-05-27T13:45:00Z',
  },
  {
    id: '21',
    title: 'Breville Espresso Machine',
    description: 'Barista Express, stainless steel. Built-in grinder, steam wand, pressure gauge. Makes excellent espresso and cappuccino. 1 year old, well maintained.',
    price: 450,
    currency: 'USD',
    imageUrl: '/images/marketplace/coffee-maker.jpg',
    category: 'Kitchen',
    condition: 'Good',
    location: 'San Francisco, CA',
    sellerId: 'user6',
    sellerName: 'David Brown',
    createdAt: '2023-05-28T09:20:00Z',
    updatedAt: '2023-05-28T09:20:00Z',
  },
  {
    id: '22',
    title: 'Vitamix Blender',
    description: 'Vitamix 5200, 64 oz container. Variable speed control, high-performance motor. Great for smoothies, soups, and more. Includes tamper and recipe book.',
    price: 280,
    currency: 'USD',
    imageUrl: '/images/marketplace/blender.jpg',
    category: 'Kitchen',
    condition: 'Good',
    location: 'Berkeley, CA',
    sellerId: 'user4',
    sellerName: 'Sarah Williams',
    createdAt: '2023-05-29T15:10:00Z',
    updatedAt: '2023-05-29T15:10:00Z',
  },
  {
    id: '23',
    title: 'Sonos One Smart Speaker',
    description: 'Gen 2, black. Voice control with Alexa and Google Assistant. Rich, room-filling sound. Works with all streaming services.',
    price: 160,
    currency: 'USD',
    imageUrl: '/images/marketplace/speaker.jpg',
    category: 'Audio',
    condition: 'Like New',
    location: 'Oakland, CA',
    sellerId: 'user7',
    sellerName: 'Emily Davis',
    createdAt: '2023-05-30T11:35:00Z',
    updatedAt: '2023-05-30T11:35:00Z',
  },
  {
    id: '24',
    title: 'Logitech MX Keys Keyboard',
    description: 'Wireless keyboard with backlit keys, USB-C charging. Multi-device capability, perfect for productivity. Used for 3 months, like new condition.',
    price: 85,
    currency: 'USD',
    imageUrl: '/images/marketplace/keyboard.jpg',
    category: 'Electronics',
    condition: 'Like New',
    location: 'Berkeley, CA',
    sellerId: 'user8',
    sellerName: 'Tom Wilson',
    createdAt: '2023-05-31T14:25:00Z',
    updatedAt: '2023-05-31T14:25:00Z',
  },
]; 